// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxvxgpwdgkeskttasrfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4dnhncHdkZ2tlc2t0dGFzcmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTY3ODYsImV4cCI6MjA2MjYzMjc4Nn0.A6d56yXTcd4OVkcr-4y9WtGI63UqzajdxqekN4EzEGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);